source("scripts/brutes/_setup.R")

tbl_NA <- tbl_custom_summary(
  df_base,
  missing = "no",
  include = c(
    -id_hemoc,
    -iep,
    -demo_centre,
    -demo_uf,
    -adm_sofa_respi,
    -adm_sofa_cardio,
    -adm_sofa_coag,
    -adm_sofa_hepatique,
    -adm_sofa_neuro,
    -hc_sofa_respi,
    -hc_sofa_cardio,
    -hc_sofa_coag,
    -hc_sofa_hepatique,
    -hc_sofa_neuro
  ),
  stat_fns = ~missing,
  statistic = everything() ~ "{N_miss} ({p_miss} %)",
  type = list(
    c(
      resultat_candida_def,
      deces_rea,
      demo_type_rea,
      demo_sexe,
      demo_atcd_hemato,
      demo_atcd_diabete,
      demo_atcd_pancreatite,
      demo_atcd_tumeur,
      adm_pancreatite_aigue,
      demo_atcd_transplantation,
      adm_choc,
      adm_vi_cat,
      adm_cgr,
      adm_pfc,
      adm_cp,
      adm_transfu,
      hc_choc,
      hc_glucanes_max,
      hc_mannanes_max,
      hc_vi_cat,
      hc_dialyse,
      hc_kta,
      hc_vvc,
      hc_ktd,
      hc_ecmo,
      hc_catheter_majeur,
      hc_cgr,
      hc_pfc,
      hc_transfu,
      hc_cp,
      hc_amines,
      hospit_fibro,
      hospit_chirurgie_majeure,
      hospit_chirurgie_abdominale,
      adm_amines
    ) ~ "dichotomous"
  ),
  value = list(
    c(
      resultat_candida_def,
      deces_rea,

      demo_atcd_hemato,
      demo_atcd_diabete,
      demo_atcd_pancreatite,
      demo_atcd_tumeur,
      adm_pancreatite_aigue,
      demo_atcd_transplantation,
      adm_choc,
      adm_vi_cat,
      adm_cgr,
      adm_pfc,
      adm_cp,
      adm_transfu,
      hc_choc,
      hc_glucanes_max,
      hc_mannanes_max,
      hc_vi_cat,
      hc_dialyse,
      hc_kta,
      hc_vvc,
      hc_ktd,
      hc_ecmo,
      hc_catheter_majeur,
      hc_transfu,
      hc_cgr,
      hc_pfc,
      hc_cp,
      hc_amines,
      hospit_fibro,
      hospit_chirurgie_majeure,
      hospit_chirurgie_abdominale,
      adm_amines
    ) ~ "Oui",
    c(hc_catheter_majeur) ~ "1",
    c(hc_glucanes_max, hc_mannanes_max) ~ "Positif",
    demo_type_rea ~ "Medicale",
    demo_sexe ~ "Masculin"
  )
) |>
  add_overall() |>
  modify_footnote_header(
    footnote = "Nombre de NA (% de NA)",
    columns = all_stat_cols()
  )
